# Generated by Django 4.2.3 on 2023-08-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dmd_danhmucchi',
            fields=[
                ('id_danhmucchi', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tenhangmuc', models.CharField(max_length=100, verbose_name='Tên hạng mục')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.CharField(max_length=100, verbose_name='Diễn giải')),
                ('status', models.IntegerField(verbose_name='Trạng thái')),
                ('sort', models.IntegerField(verbose_name='Soft')),
                ('createat', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updateat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Danh mục chi',
                'verbose_name_plural': 'Danh mục chi',
            },
        ),
        migrations.CreateModel(
            name='dmd_typenganhang',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False, verbose_name='ID loại')),
                ('tenloai', models.CharField(max_length=50, verbose_name='Loại tài khoản')),
                ('status', models.IntegerField(verbose_name='Trạng thái')),
                ('createat', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updateat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Loại tài khoản ngân hàng',
                'verbose_name_plural': 'Loại tài khoản ngân hàng',
            },
        ),
        migrations.CreateModel(
            name='dmd_nganhang',
            fields=[
                ('id_nganhang', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Ngân hàng')),
                ('tennganhang', models.CharField(max_length=100, verbose_name='Tên ngân hàng')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.CharField(max_length=100, verbose_name='Diễn giải')),
                ('tengiaodich', models.CharField(max_length=200, verbose_name='Tên giao dịch')),
                ('stk', models.CharField(max_length=50, verbose_name='Số tài khoản')),
                ('status', models.IntegerField(choices=[(1, 'Hoạt động'), (2, 'Tạm ngưng')], verbose_name='Trạng thái')),
                ('createat', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updateat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dmd_typenganhang', verbose_name='Loại tài khoản')),
            ],
            options={
                'verbose_name': 'Danh mục Ngân hàng',
                'verbose_name_plural': 'Danh mục Ngân hàng',
            },
        ),
        migrations.CreateModel(
            name='dmd_chitieu',
            fields=[
                ('id_chitieu', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_sotien', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Số tiền')),
                ('description', models.TextField(verbose_name='Diễn giải')),
                ('ct_ngaychi', models.DateTimeField(auto_now_add=True, verbose_name='Ngày chi')),
                ('status', models.IntegerField(verbose_name='Trạng thái')),
                ('recyclebin', models.IntegerField(verbose_name='Đã xóa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày cập nhật')),
                ('id_danhmucchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dmd_danhmucchi', verbose_name='ID danh mục chi')),
                ('id_nganhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dmd_nganhang', verbose_name='ID Ngân hàng')),
            ],
            options={
                'verbose_name': 'Danh sách chi tiêu',
                'verbose_name_plural': 'Danh sách chi tiêu',
            },
        ),
    ]
