# Generated by Django 4.2.3 on 2023-08-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmd_danhmucchi',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dmd_nganhang',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
