# Generated by Django 4.2.3 on 2023-08-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_dmd_danhmucchi_slug_alter_dmd_nganhang_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmd_danhmucchi',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='dmd_nganhang',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
